/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ParkingSpot, ParkingStatus, VehicleType, CityEvent, AvailabilityType } from './types';

export const UPCOMING_EVENTS: CityEvent[] = [
  {
    id: 'e1',
    name: 'Festival Kesenian Yogyakarta',
    description: 'Perayaan seni dan budaya tahunan terbesar di Yogyakarta dengan berbagai pertunjukan dan pameran.',
    location: 'Km 0 Yogyakarta & Malioboro',
    coordinates: { lat: -7.8014, lng: 110.3648 },
    category: 'Cultural',
    city: 'Yogyakarta',
    date: '15 Mei 2026',
    time: '10:00 - 22:00',
    image: 'https://images.unsplash.com/photo-1543165796-5426273ea498?q=80&w=800&auto=format&fit=crop',
    expectedCrowd: 'High'
  },
  {
    id: 'e2',
    name: 'Konser Musik Indie Jogja',
    description: 'Menampilkan band-band lokal terbaik Yogyakarta dalam satu panggung spektakuler.',
    location: 'Stadion Mandala Krida',
    coordinates: { lat: -7.7936, lng: 110.3855 },
    category: 'Concert',
    city: 'Yogyakarta',
    date: '20 Mei 2026',
    time: '18:00 - 23:00',
    image: 'https://images.pexels.com/photos/4481259/pexels-photo-4481259.jpeg?auto=compress&cs=tinysrgb&w=800',
    expectedCrowd: 'Medium'
  },
  {
    id: 'e3',
    name: 'Yogyakarta Tech Expo',
    description: 'Pameran teknologi dan inovasi startup terbesar di Jawa Tengah dan DIY.',
    location: 'Jogja Expo Center',
    coordinates: { lat: -7.7981, lng: 110.4014 },
    category: 'Exhibition',
    city: 'Yogyakarta',
    date: '22-25 Mei 2026',
    time: '09:00 - 21:00',
    image: 'https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?q=80&w=800&auto=format&fit=crop',
    expectedCrowd: 'Medium'
  }
];

export const DUMMY_SPOTS: ParkingSpot[] = [
  {
    id: '1',
    name: 'Garasi Pak Budi',
    ownerName: 'Budi Santoso',
    ownerId: 'admin-seed-1',
    address: 'Jl. Malioboro No. 45, Yogyakarta',
    pricePerHour: 5000,
    capacity: {
      [VehicleType.MOTOR]: 5,
      [VehicleType.MOBIL]: 1,
    },
    rating: 4.8,
    reviewsCount: 124,
    coordinates: { lat: -7.7926, lng: 110.3658 },
    images: ['https://images.unsplash.com/photo-1590674412391-7f749658e184?q=80&w=800&auto=format&fit=crop'],
    features: ['CCTV', 'Atap', 'Dekat Malioboro'],
    isVerified: true,
    safetyScore: 95,
    status: ParkingStatus.AVAILABLE,
    description: 'Halaman rumah luas, aman, ada pagar dan CCTV. Sangat dekat dengan pintu masuk utama Malioboro Mall.',
    availabilityType: AvailabilityType.PERMANENT,
    activeEventIds: ['e1'],
    eventPricing: { 'e1': 8000 }
  },
  {
    id: '2',
    name: 'Parkiran Dekat Tugu',
    ownerName: 'Siti Aminah',
    ownerId: 'admin-seed-2',
    address: 'Jl. P. Mangkubumi No. 12, Yogyakarta',
    pricePerHour: 3000,
    capacity: {
      [VehicleType.MOTOR]: 10,
      [VehicleType.MOBIL]: 0,
    },
    rating: 4.5,
    reviewsCount: 89,
    coordinates: { lat: -7.7829, lng: 110.3671 },
    images: ['https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?q=80&w=800&auto=format&fit=crop'],
    features: ['Murah', '24 Jam'],
    isVerified: true,
    safetyScore: 88,
    status: ParkingStatus.AVAILABLE,
    description: 'Khusus motor. Lokasi strategis dekat Tugu Jogja. Bisa parkir harian atau jam-jaman.',
    availabilityType: AvailabilityType.PERMANENT,
  },
  {
    id: '3',
    name: 'Lahan Kosong Mas Agus',
    ownerName: 'Agus Prayitno',
    ownerId: 'admin-seed-3',
    address: 'Jl. Sosrowijayan No. 2, Yogyakarta',
    pricePerHour: 7000,
    capacity: {
      [VehicleType.MOTOR]: 2,
      [VehicleType.MOBIL]: 3,
    },
    rating: 4.2,
    reviewsCount: 45,
    coordinates: { lat: -7.7892, lng: 110.3631 },
    images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=800&auto=format&fit=crop'],
    features: ['Luas', 'Pagar Keliling'],
    isVerified: false,
    safetyScore: 75,
    status: ParkingStatus.AVAILABLE,
    description: 'Lahan kosong berpagar. Cocok untuk mobil keluarga atau minibus.',
    availabilityType: AvailabilityType.PERMANENT,
  },
  {
    id: '4',
    name: 'Halaman Event Mandala',
    ownerName: 'Eko Wahyudi',
    ownerId: 'admin-seed-4',
    address: 'Samping Stadion Mandala Krida',
    pricePerHour: 4000,
    capacity: {
      [VehicleType.MOTOR]: 20,
      [VehicleType.MOBIL]: 5,
    },
    rating: 4.0,
    reviewsCount: 12,
    coordinates: { lat: -7.7940, lng: 110.3860 },
    images: ['https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=800&auto=format&fit=crop'],
    features: ['Hanya saat Event', 'Sangat Luas'],
    isVerified: true,
    safetyScore: 80,
    status: ParkingStatus.AVAILABLE,
    description: 'Lahan hanya dibuka saat ada event di Mandala Krida atau wilayah Umbulharjo.',
    availabilityType: AvailabilityType.TEMPORARY,
    startDate: '2026-05-18',
    endDate: '2026-05-22',
    operatingHours: '16:00 - 23:00',
    relatedEventName: 'Konser Musik Indie Jogja',
    isEventOnly: true,
    activeEventIds: ['e2'],
    eventPricing: { 'e2': 10000 }
  },
  {
    id: '5',
    name: 'Spot JEC Premium',
    ownerName: 'Hendra Wijaya',
    ownerId: 'admin-seed-5',
    address: 'Jl. Raya Janti No. 5, Yogyakarta',
    pricePerHour: 6000,
    capacity: {
      [VehicleType.MOTOR]: 15,
      [VehicleType.MOBIL]: 4,
    },
    rating: 4.9,
    reviewsCount: 56,
    coordinates: { lat: -7.7990, lng: 110.4020 },
    images: ['https://images.unsplash.com/photo-1495433331362-d44aa5517bc6?q=80&w=800&auto=format&fit=crop'],
    features: ['Penerangan Baik', 'Beraspal'],
    isVerified: true,
    safetyScore: 92,
    status: ParkingStatus.AVAILABLE,
    description: 'Tepat di seberang JEC. Sangat mudah akses masuk dan keluar untuk mobil besar.',
    availabilityType: AvailabilityType.PERMANENT,
    activeEventIds: ['e3'],
    eventPricing: { 'e3': 12000 }
  },
  {
    id: '6',
    name: 'Halaman Alkif Home',
    ownerName: 'Danang',
    ownerId: 'admin-seed-6',
    address: 'Jl. Langenastran Kidul, Alun-Alun Kidul',
    pricePerHour: 5000,
    capacity: {
      [VehicleType.MOTOR]: 30,
      [VehicleType.MOBIL]: 0,
    },
    rating: 4.7,
    reviewsCount: 210,
    coordinates: { lat: -7.8118, lng: 110.3634 },
    images: ['https://images.unsplash.com/photo-1545179605-1296651e9d43?q=80&w=800&auto=format&fit=crop'],
    features: ['Dekat Kuliner', 'Dijaga Pemilik'],
    isVerified: true,
    safetyScore: 90,
    status: ParkingStatus.AVAILABLE,
    description: 'Sangat dekat dengan pusat keramaian Alun-Alun Kidul. Aman untuk parkir malam.',
    availabilityType: AvailabilityType.PERMANENT,
  },
  {
    id: '7',
    name: 'Parkiran Dekat Grha Sabha UGM',
    ownerName: 'Iwan',
    ownerId: 'admin-seed-7',
    address: 'Kawasan Wisma UGM, Bulaksumur',
    pricePerHour: 4000,
    capacity: {
      [VehicleType.MOTOR]: 12,
      [VehicleType.MOBIL]: 2,
    },
    rating: 4.4,
    reviewsCount: 34,
    coordinates: { lat: -7.7716, lng: 110.3803 },
    images: ['https://images.unsplash.com/photo-1516515429572-1f997c67975e?q=80&w=800&auto=format&fit=crop'],
    features: ['Teduh', 'Akses Kampus'],
    isVerified: true,
    safetyScore: 85,
    status: ParkingStatus.AVAILABLE,
    description: 'Area tenang, teduh banyak pohon. Pas untuk yang mau ke Grha Sabha atau Fakultas di UGM.',
    availabilityType: AvailabilityType.PERMANENT,
  },
  {
    id: '8',
    name: 'Pusat Nol KM Spot',
    ownerName: 'Heru',
    ownerId: 'admin-seed-8',
    address: 'Dekat Gedung Agung, Titik Nol Jogja',
    pricePerHour: 8000,
    capacity: {
      [VehicleType.MOTOR]: 20,
      [VehicleType.MOBIL]: 1,
    },
    rating: 4.6,
    reviewsCount: 156,
    coordinates: { lat: -7.8012, lng: 110.3642 },
    images: ['https://images.unsplash.com/photo-1590674852885-8c6424b33343?q=80&w=800&auto=format&fit=crop'],
    features: ['Sangat Strategis', 'CCTV'],
    isVerified: true,
    safetyScore: 98,
    status: ParkingStatus.AVAILABLE,
    description: 'Spot paling premium di Titik Nol. Hanya 30 detik jalan kaki ke kawasan wisata utama.',
    availabilityType: AvailabilityType.PERMANENT,
  },
  {
    id: '9',
    name: 'Prambanan View Parking',
    ownerName: 'Mbah Jo',
    ownerId: 'admin-seed-9',
    address: 'Kawasan Wisata Prambanan, Sleman',
    pricePerHour: 5000,
    capacity: {
      [VehicleType.MOTOR]: 10,
      [VehicleType.MOBIL]: 10,
    },
    rating: 4.3,
    reviewsCount: 23,
    coordinates: { lat: -7.7521, lng: 110.4912 },
    images: ['https://images.unsplash.com/photo-1543332164-6e82f355bab1?q=80&w=800&auto=format&fit=crop'],
    features: ['View Candi', 'Parkir Luas'],
    isVerified: false,
    safetyScore: 82,
    status: ParkingStatus.AVAILABLE,
    description: 'Halaman rumah sangat luas, muat banyak mobil. Dekat pintu masuk wisata Candi Prambanan.',
    availabilityType: AvailabilityType.PERMANENT,
  },
  {
    id: '10',
    name: 'Garasi Festival Sekaten',
    ownerName: 'Pak Slamet',
    ownerId: 'admin-seed-10',
    address: 'Alun-Alun Utara, Yogyakarta',
    pricePerHour: 10000,
    capacity: {
      [VehicleType.MOTOR]: 40,
      [VehicleType.MOBIL]: 0,
    },
    rating: 4.9,
    reviewsCount: 12,
    coordinates: { lat: -7.8025, lng: 110.3644 },
    images: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop'],
    features: ['Khusus Event', 'Sangat Dekat'],
    isVerified: true,
    safetyScore: 96,
    status: ParkingStatus.AVAILABLE,
    description: 'Hanya buka selama Festival Sekaten berlangsung. Lokasi tepat di depan pintu masuk festival.',
    availabilityType: AvailabilityType.TEMPORARY,
    startDate: '2026-05-12',
    endDate: '2026-05-25',
    operatingHours: '10:00 - 23:59',
    relatedEventName: 'Festival Sekaten',
    isEventOnly: true,
  },
  {
    id: '11',
    name: 'Halaman Belakang Tech Expo',
    ownerName: 'Mbak Maya',
    ownerId: 'admin-seed-11',
    address: 'Kawasan JEC, Banguntapan',
    pricePerHour: 5000,
    capacity: {
      [VehicleType.MOTOR]: 5,
      [VehicleType.MOBIL]: 5,
    },
    rating: 0,
    reviewsCount: 0,
    coordinates: { lat: -7.7985, lng: 110.4025 },
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop'],
    features: ['Aman', 'Pagar Keliling'],
    isVerified: false,
    safetyScore: 85,
    status: ParkingStatus.COMING_SOON,
    description: 'Dibuka khusus selama Tech Expo berlangsung. Lokasi aman di halaman belakang rumah yang berpagar.',
    availabilityType: AvailabilityType.TEMPORARY,
    startDate: '2026-05-22',
    endDate: '2026-05-25',
    operatingHours: '08:00 - 21:00',
    relatedEventName: 'Yogyakarta Tech Expo',
  }
];
